Project1.WebApp/ViewModels/LocationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Project1.WebApp.ViewModels
{
    public class LocationViewModel
    {
        [Display(Name = "Location ID")]
        public int LocationID { get; set; }


        [Display(Name = "Location Name")]
        public string Name { get; set; }

        [Display(Name = "How to get from here to There")]
        public string Address { get; set; }

        public IEnumerable<OrderHistoryViewModel> OrderHistoryViewModels { get; set; }

        public IEnumerable<InventoryViewModel> InventoryViewModels { get; set; }

    }
}

Project1.WebApp/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project1.Domain;
using Project1.WebApp.ViewModels;

namespace Project1.WebApp.Controllers
{
    public class LocationController : Controller
    {

        private readonly ILocationRepository _locationRepo;
        private readonly IOrderHistoryRepository _orderhistoryRepo;
        private readonly IInventoryRepository _inventoryRepo;
        private readonly IOrdersRepository _ordersRepo;

        public LocationController(ILocationRepository locationRepo, IOrderHistoryRepository orderHistoryRepo, IInventoryRepository inventoryRepo, IOrdersRepository ordersRepo)
        {
            _locationRepo = locationRepo ?? throw new ArgumentNullException(nameof(locationRepo));
            _orderhistoryRepo = orderHistoryRepo ?? throw new ArgumentNullException(nameof(orderHistoryRepo));
            _inventoryRepo = inventoryRepo ?? throw new ArgumentNullException(nameof(inventoryRepo));
            _ordersRepo = ordersRepo ?? throw new ArgumentNullException(nameof(ordersRepo));
        }

        public IActionResult Index()
        {

            var viewModel = _locationRepo.GetAll().Select(a => new LocationViewModel
            {
                LocationID = a.LocationID,
                Name = a.Name,
                Address = a.Address
            });

            //setting up shopping cart
            HttpContext.Response.Cookies.Append("ProID1", "0");
            HttpContext.Response.Cookies.Append("ProID2", "0");
            HttpContext.Response.Cookies.Append("ProID3", "0");
            HttpContext.Response.Cookies.Append("ProID4", "0");
            HttpContext.Response.Cookies.Append("ProID5", "0");
            HttpContext.Response.Cookies.Append("PA1", "0");
            HttpContext.Response.Cookies.Append("PA2", "0");
            HttpContext.Response.Cookies.Append("PA3", "0");
            HttpContext.Response.Cookies.Append("PA4", "0");
            HttpContext.Response.Cookies.Append("PA5", "0");
            return View(viewModel);
        }

        public ActionResult Details(int id, bool c)
        {
            if (c == false)
            {
                HttpContext.Response.Cookies.Append("Customer", "false");
            };

            if (id != 0)
            {
                HttpContext.Response.Cookies.Append("LocationID", $"{id}");
            }
            else
            {
                id = int.Parse(HttpContext.Request.Cookies["LocationID"]);
            }
            
            Location location = _locationRepo.GetLocationByID(id);
            var viewModel = new LocationViewModel
            {
                LocationID = location.LocationID,
                Name = location.Name,
                Address = location.Address,
                InventoryViewModels = _inventoryRepo.GetInventoryById(id).Select(m => new InventoryViewModel
                {
                    LocationId = m.LocationId,
                    ProductId = m.ProductId,
                    Name = m.Name,
                    Price = m.Price,
                    Amount = m.Amount
                }),
                OrderHistoryViewModels = _orderhistoryRepo.GetOrderHistoryByLocationId(id).Select(y => new OrderHistoryViewModel
                {
                    LocationId = y.LocationId,
                    OrderId = y.OrderId,
                    CustomerId = y.CustomerId,
                    Date = y.Date,
                    Time = y.Time
                })
            };


            return View(viewModel);
        }

      
        public ActionResult Shop(int id)
        {
            Location location = _locationRepo.GetLocationByID(id);
            var viewModel = new LocationViewModel
            {
                LocationID = location.LocationID,
                Name = location.Name,
                Address = location.Address,
                InventoryViewModels = _inventoryRepo.GetInventoryById(id).Select(m => new InventoryViewModel
                {
                    LocationId = m.LocationId,
                    ProductId = m.ProductId,
                    Name = m.Name,
                    Price = m.Price,
                    Amount = m.Amount
                })
            };
            //display shopping cart
            

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Shop(int ProductID, int PurchaseAmount)
        {
            //must place order validation here, such that one cannot over order an item



            int Locationid = int.Parse(HttpContext.Request.Cookies["LocationID"]);
            int customerid = int.Parse(HttpContext.Request.Cookies["CustomerID"]);


            if (ProductID != 0 && PurchaseAmount != 0)
            {
                
                HttpContext.Response.Cookies.Append("ProID"+$"{ProductID}", $"{ProductID}");
                HttpContext.Response.Cookies.Append("PA"+$"{ProductID}", $"{PurchaseAmount}");
            }



            Location location = _locationRepo.GetLocationByID(Locationid);
            var viewModel = new LocationViewModel
            {
                LocationID = location.LocationID,
                Name = location.Name,
                Address = location.Address,
                InventoryViewModels = _inventoryRepo.GetInventoryById(Locationid).Select(m => new InventoryViewModel
                {
                    LocationId = m.LocationId,
                    ProductId = m.ProductId,
                    Name = m.Name,
                    Price = m.Price,
                    Amount = m.Amount
                })
            };

            


            return View(viewModel);

        }


        public ActionResult CompleteOrder()
        {
            //finalize the order from cart

            //shopping cart data
            int Locationid = int.Parse(HttpContext.Request.Cookies["LocationID"]);
            int customerid = int.Parse(HttpContext.Request.Cookies["CustomerID"]);
            int ProductID1 = int.Parse(HttpContext.Request.Cookies["ProID1"]);
            int ProductID2 = int.Parse(HttpContext.Request.Cookies["ProID2"]);
            int ProductID3 = int.Parse(HttpContext.Request.Cookies["ProID3"]);
            int ProductID4 = int.Parse(HttpContext.Request.Cookies["ProID4"]);
            int ProductID5 = int.Parse(HttpContext.Request.Cookies["ProID5"]);
            int Amount1 = int.Parse(HttpContext.Request.Cookies["PA1"]);
            int Amount2 = int.Parse(HttpContext.Request.Cookies["PA2"]);
            int Amount3 = int.Parse(HttpContext.Request.Cookies["PA3"]);
            int Amount4 = int.Parse(HttpContext.Request.Cookies["PA4"]);
            int Amount5 = int.Parse(HttpContext.Request.Cookies["PA5"]);

            //New Order History
            OrderHistory orderHistory = new OrderHistory
            {
                LocationId = Locationid,
                CustomerId = customerid
            };
            _orderhistoryRepo.Create(orderHistory);


            //The new Order ID
            int orderid = _orderhistoryRepo.GetAll().Count();

            //note to self, compress next step into dynamic
            //new orders
            if (ProductID1 == 1)
            {
                Inventory inventory1 = new Inventory
                {
                    LocationId = Locationid,
                    ProductId = ProductID1,
                    Amount = Amount1
                };
                
                Orders orders1 = new Orders
                {
                    OrderID = orderid,
                    ProductID = ProductID1,
                    Amount = Amount1
                };
                //finalize
                _inventoryRepo.Update(inventory1);
                _ordersRepo.Create(orders1);
            }
            if (ProductID2 == 2)
            {
                Inventory inventory2 = new Inventory
                {
                    LocationId = Locationid,
                    ProductId = ProductID2,
                    Amount = Amount2
                };

                Orders orders2 = new Orders
                {
                    OrderID = orderid,
                    ProductID = ProductID2,
                    Amount = Amount2
                };
                //finalize
                _inventoryRepo.Update(inventory2);
                _ordersRepo.Create(orders2);
            }
            if (ProductID3 == 3)
            {
                Inventory inventory3 = new Inventory
                {
                    LocationId = Locationid,
                    ProductId = ProductID3,
                    Amount = Amount3
                };

                Orders orders3 = new Orders
                {
                    OrderID = orderid,
                    ProductID = ProductID3,
                    Amount = Amount3
                };
                //finalize
                _inventoryRepo.Update(inventory3);
                _ordersRepo.Create(orders3);
            }
            if (ProductID4 == 4)
            {
                Inventory inventory4 = new Inventory
                {
                    LocationId = Locationid,
                    ProductId = ProductID4,
                    Amount = Amount4
                };

                Orders orders4 = new Orders
                {
                    OrderID = orderid,
                    ProductID = ProductID4,
                    Amount = Amount4
                };
                //finalize
                _inventoryRepo.Update(inventory4);
                _ordersRepo.Create(orders4);
            }
            if (ProductID5 == 5)
            {
                Inventory inventory5 = new Inventory
                {
                    LocationId = Locationid,
                    ProductId = ProductID5,
                    Amount = Amount5
                };

Project1.WebApp/Controllers/OrderHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project1.Domain;
using Project1.WebApp.ViewModels;

namespace Project1.WebApp.Controllers
{
    public class OrderHistoryController : Controller
    {
        private readonly IOrderHistoryRepository _orderhistoryRepo;
        private readonly IOrdersRepository _ordersRepo;

        public OrderHistoryController(IOrderHistoryRepository orderhistoryRepo, IOrdersRepository ordersRepo)
        {
            _orderhistoryRepo = orderhistoryRepo ?? throw new ArgumentNullException(nameof(orderhistoryRepo));
            _ordersRepo = ordersRepo ?? throw new ArgumentNullException(nameof(ordersRepo));
        }



        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderHistoryViewModel viewModel)
        {

            return View(viewModel);
        }


        public ActionResult Details(int id)
        {
            
            OrderHistory orderHistory = _orderhistoryRepo.GetOrderHistoryByOrderId(id);
            var viewModel = new OrderHistoryViewModel
            {
                OrderId = orderHistory.OrderId,
                LocationId = orderHistory.LocationId,
                CustomerId = orderHistory.CustomerId,
                Date = orderHistory.Date,
                Time = orderHistory.Time,
                Orders = _ordersRepo.GetOrdersByOrderId(id).Select(t => new OrdersViewModel
                {
                    OrderID = t.OrderID,
                    ProductID = t.ProductID,
                    Name = t.Name,
                    Amount = t.Amount
                })
            };

            return View(viewModel);
        }


       
    }
}

Project1.WebApp/Views/Location/Details.cshtml
@model Project1.WebApp.ViewModels.LocationViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Location Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<div>
    @if (Model.InventoryViewModels.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().LocationId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().ProductId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().Amount)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.InventoryViewModels)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.LocationId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>




<div>
    <br />
    <div class="text-right">
        @if (Context.Request.Cookies["CustomerID"] != null && Context.Request.Cookies["CustomerID"] != "0")
        {
        <p>
            @Html.ActionLink("Place New Order", "Shop", new { id = Model.LocationID})
        </p>
        }
    </div>
    <br />
    <br />
    <h3 class="text-center">Order History</h3>
    @if (Model.OrderHistoryViewModels.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(Model => Model.OrderHistoryViewModels.FirstOrDefault().OrderId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.OrderHistoryViewModels.FirstOrDefault().LocationId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.OrderHistoryViewModels.FirstOrDefault().CustomerId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.OrderHistoryViewModels.FirstOrDefault().Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.OrderHistoryViewModels.FirstOrDefault().Time)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderHistoryViewModels)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "OrderHistory", new { id = item.OrderId}, null)
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Project1.WebApp/Views/Location/Index.cshtml
@model IEnumerable<Project1.WebApp.ViewModels.LocationViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Store Locations</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LocationID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LocationID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.LocationID , c = false})
                </td>
            </tr>
        }
    </tbody>
</table>

Project1.WebApp/Views/Location/Shop.cshtml
@model Project1.WebApp.ViewModels.LocationViewModel

@{
    ViewData["Title"] = "Shop";
}

<h1>Details</h1>

<div>
    <h4>Location Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LocationID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LocationID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Details">Back to Location Details</a>
</div>
<div>
    @if (Model.InventoryViewModels.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().LocationId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().ProductId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(Model => Model.InventoryViewModels.FirstOrDefault().Amount)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.InventoryViewModels)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.LocationId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    @using (Html.BeginForm())
    {
        <form>
            <div>
                <label for="ProductID">Enter Product ID</label>
                <input type="number" value="ID" name="ProductID" min="1" max="5"/>
            </div>
            <div>
                <label for="PurchaseAmount">Enter Amount</label>
                <input type="number" value="amount" name="PurchaseAmount" min="1" />
            </div>
            <div>
                <input type="submit" value="Save" />
            </div>
        </form>
    }
</div>





<div>
    <h2 class="text-center">Shopping Cart</h2>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Product ID
                </th>
                <th>
                    Amount Selected
                </th>
            </tr>
        </thead>
        <tbody>

            @if (int.Parse(@Context.Request.Cookies["ProID1"]) != 0)
            {
                <tr>
                    <td>
                        @Context.Request.Cookies["ProID1"]
                    </td>
                    <td>
                        @Context.Request.Cookies["PA1"]
                    </td>
                </tr>
            }
            @if (int.Parse(@Context.Request.Cookies["ProID2"]) != 0)
            {
                <tr>
                    <td>
                        @Context.Request.Cookies["ProID2"]
                    </td>
                    <td>
                        @Context.Request.Cookies["PA2"]
                    </td>
                </tr>
            }
            @if (int.Parse(@Context.Request.Cookies["ProID3"]) != 0)
            {
                <tr>
                    <td>
                        @Context.Request.Cookies["ProID3"]
                    </td>
                    <td>
                        @Context.Request.Cookies["PA3"]
                    </td>
                </tr>
            }
            @if (int.Parse(@Context.Request.Cookies["ProID4"]) != 0)
            {
                <tr>
                    <td>
                        @Context.Request.Cookies["ProID4"]
                    </td>
                    <td>
                        @Context.Request.Cookies["PA4"]
                    </td>
                </tr>
            }
            @if (int.Parse(@Context.Request.Cookies["ProID5"]) != 0)
            {
                <tr>
                    <td>
                        @Context.Request.Cookies["ProID5"]
                    </td>
                    <td>
                        @Context.Request.Cookies["PA5"]
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (int.Parse(@Context.Request.Cookies["ProID1"]) != 0 || int.Parse(@Context.Request.Cookies["ProID2"]) != 0 || int.Parse(@Context.Request.Cookies["ProID3"]) != 0 || int.Parse(@Context.Request.Cookies["ProID4"]) != 0 || int.Parse(@Context.Request.Cookies["ProID5"]) != 0)
    {
        @Html.ActionLink("Complete Order", "CompleteOrder")
    }

</div>